server:
  context-path: /sessiontest
  port: 8001
spring:
  redis:
    database: 0
    host: 106.15.224.229
    port: 6379
    password: dev34516
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    timeout: 0
  session:
    store-type: redis
    timeout: 10
